import React,{useState,useReducer,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {initialGuard,guardReducer,normalizeDomain,validTime,timeInRange,activeRule,blockedReason,contentHidden,health,scanSites} from './browser-guard-state.mjs';

const icons={
  shield:<><path d="m12 2 9 4v6c0 5-9 10-9 10S3 17 3 12V6z"/><path d="m8 12 3 3 5-6"/></>,
  globe:<><circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/></>,
  clock:<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>,
  content:<><path d="m12 3 2 6 7 3-7 2-2 7-2-7-7-2 7-3z"/></>,
  lock:<><rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V6a4 4 0 0 1 8 0v4"/></>,
  close:<path d="m6 6 12 12M6 18 18 6"/>,
  back:<path d="m14 6-6 6 6 6"/>,
  reset:<><path d="m8 4-5 5 5 5M3 9h10a7 7 0 0 1 0 14"/></>,
};
function Icon({name}) {return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{icons[name]}</svg>;}
function Brand() {return <div className="bgd-brand"><span><Icon name="shield"/></span><div><strong>Layers Guard</strong><small>Calm, local protection for the web</small></div></div>;}
function Badge({state}) {const h=health(state);return <span className={`bgd-badge ${h.kind}`}>{h.title}</span>;}
function Toggle({label,checked,onChange}) {return <label className="bgd-switch"><input type="checkbox" aria-label={label} checked={checked} onChange={onChange}/><span aria-hidden="true"/></label>;}
function Times({start,end,setStart,setEnd,prefix}) {return <div className="bgd-times"><label>From<input type="time" aria-label={`${prefix} start`} value={start} onInput={e=>setStart(e.target.value)} onChange={e=>setStart(e.target.value)}/></label><label>To<input type="time" aria-label={`${prefix} end`} value={end} onInput={e=>setEnd(e.target.value)} onChange={e=>setEnd(e.target.value)}/></label></div>;}
function Alerts({state,clear}) {return <div className="bgd-card"><div className="bgd-row"><div><h4>Safety alerts</h4><p>Sample metadata only: category, website and time.</p></div>{clear&&<button disabled={!state.alerts.length} onClick={clear}>Clear history</button>}</div>{state.alerts.length?state.alerts.map(a=><div className="bgd-alert" key={a.id}><span className={`bgd-severity ${a.severity.toLowerCase()}`}>{a.severity}</span><div><strong>{a.category}</strong><small>{a.domain} · {a.time}</small></div><span>{a.read?'Reviewed':'New'}</span></div>):<p className="bgd-empty">No sample alerts yet. Try the content example in Sample browsing.</p>}</div>;}

function Websites({state,dispatch,notify}) {
  const [input,setInput]=useState(''),[scheduled,setScheduled]=useState(false),[start,setStart]=useState('16:00'),[end,setEnd]=useState('18:00'),[error,setError]=useState(''),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[editing,setEditing]=useState(''),[editStart,setEditStart]=useState(''),[editEnd,setEditEnd]=useState(''),[editScheduled,setEditScheduled]=useState(false),[recommended,setRecommended]=useState(false),[selected,setSelected]=useState(['instagram.com','netflix.com']);
  function add(e) {e.preventDefault();const domain=normalizeDomain(input);if(!domain){setError('Enter a domain or an http/https URL, for example youtube.com.');return;}if(state.rules.some(r=>r.domain===domain)){setError('That website already has a rule. Edit it below.');return;}if(scheduled&&(!validTime(start)||!validTime(end)||start===end)){setError('Choose different start and end times.');return;}dispatch({type:'rule',value:{domain,enabled:true,schedule:scheduled?{start,end}:null}});setInput('');setError('');notify(`Added ${domain} to the sample rules.`);}
  const rules=state.rules.filter(r=>r.domain.includes(search.toLowerCase())&&(filter==='all'||filter==='active'&&activeRule(r,state.time)||filter==='always'&&!r.schedule||filter==='scheduled'&&r.schedule));
  return <><div className="bgd-card"><h4>Add a website</h4><form onSubmit={add}><div className="bgd-add-row"><label className="bgd-grow">Website domain<input value={input} aria-label="Website domain" placeholder="youtube.com" onChange={e=>setInput(e.target.value)}/></label><button className="bgd-primary">Block website</button></div><p>Paste a domain or URL. Paths and query strings are removed.</p><label className="bgd-check"><input type="checkbox" checked={scheduled} onChange={e=>setScheduled(e.target.checked)}/>Block only during specific hours</label>{scheduled&&<Times start={start} end={end} setStart={setStart} setEnd={setEnd} prefix="Website rule"/>}{error&&<p className="bgd-error" role="alert">{error}</p>}</form></div>
    <label className="bgd-search">Search blocked websites<input type="search" aria-label="Search blocked websites" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="bgd-filters" aria-label="Website rule filters">{[['all','All'],['active','Active now'],['always','Always'],['scheduled','Scheduled']].map(([f,label])=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{label}</button>)}</div>
    <div className="bgd-rule-list">{rules.length?rules.map(r=><div className="bgd-rule" key={r.domain}><div className="bgd-row"><div><strong>{r.domain}</strong><small>{!r.enabled?'Paused':r.schedule?`${r.schedule.start}–${r.schedule.end} · ${activeRule(r,state.time)?'Blocked now':'Scheduled'}`:'Always blocked'}</small></div><span className={`bgd-rule-state ${activeRule(r,state.time)?'active':''}`}>{activeRule(r,state.time)?'Active now':r.enabled?'Scheduled':'Paused'}</span></div><div className="bgd-rule-actions"><button aria-label={`${r.enabled?'Pause':'Resume'} ${r.domain}`} onClick={()=>dispatch({type:'toggle-rule',domain:r.domain})}>{r.enabled?'Pause':'Resume'}</button><button aria-label={`Edit ${r.domain}`} onClick={()=>{setEditing(editing===r.domain?'':r.domain);setEditScheduled(Boolean(r.schedule));setEditStart(r.schedule?.start||'16:00');setEditEnd(r.schedule?.end||'18:00');}}>Edit</button><button aria-label={`Remove ${r.domain}`} onClick={()=>{dispatch({type:'remove-rule',domain:r.domain});notify(`Removed ${r.domain} from the sample rules.`);}}>Remove</button></div>{editing===r.domain&&<form className="bgd-edit" onSubmit={e=>{e.preventDefault();if(editScheduled&&(!validTime(editStart)||!validTime(editEnd)||editStart===editEnd))return;dispatch({type:'rule',value:{...r,schedule:editScheduled?{start:editStart,end:editEnd}:null}});setEditing('');notify('Sample rule updated.');}}><label className="bgd-check"><input type="checkbox" checked={editScheduled} onChange={e=>setEditScheduled(e.target.checked)}/>Block only during specific hours</label>{editScheduled&&<Times prefix="Edited rule" start={editStart} end={editEnd} setStart={setEditStart} setEnd={setEditEnd}/>}<div className="bgd-rule-actions"><button type="button" onClick={()=>setEditing('')}>Cancel</button><button className="bgd-primary" disabled={editScheduled&&(!validTime(editStart)||!validTime(editEnd)||editStart===editEnd)}>Save changes</button></div></form>}</div>):<p className="bgd-empty">No matching website rules.</p>}</div>
    <div className="bgd-card"><div className="bgd-row"><div><h4>Recommended websites</h4><p>Try a few domains from the extension’s recommended list.</p></div><button onClick={()=>setRecommended(!recommended)} aria-expanded={recommended}>{recommended?'Close list':'Choose websites'}</button></div>{recommended&&<><div className="bgd-monitored">{['instagram.com','netflix.com','discord.com','poki.com'].map(d=><label className="bgd-check" key={d}><input type="checkbox" checked={selected.includes(d)} onChange={()=>setSelected(s=>s.includes(d)?s.filter(x=>x!==d):[...s,d])}/>{d}</label>)}</div><button className="bgd-primary" disabled={!selected.length} onClick={()=>{selected.forEach(domain=>{if(!state.rules.some(r=>r.domain===domain))dispatch({type:'rule',value:{domain,enabled:true,schedule:null}});});setRecommended(false);notify('Selected sample websites added.');}}>Add selected websites</button></>}</div>
  </>;
}
function ParentControls({state,dispatch,tab,setTab,locked,setLocked,notify,resetId}) {
  const [pin,setPin]=useState(''),[pinError,setPinError]=useState('');
  const titles={overview:'Protection status',websites:'Blocked websites',schedule:'Bedtime Protection',content:'Content Protection',settings:'Settings'};
  function enter(value) {setPin(value.replace(/\D/g,'').slice(0,4));setPinError('');}
  if(locked)return <div className="bgd-auth"><Brand/><div className="bgd-pin-card"><span className="bgd-kicker">Parent Controls</span><h3>Enter your PIN</h3><p>Use the sample PIN <strong>1234</strong> to explore the parent controls.</p><form onSubmit={e=>{e.preventDefault();if(pin==='1234'){setLocked(false);setPin('');setPinError('');notify('Sample Parent Controls unlocked.');}else{setPinError('Try the sample PIN: 1234.');setPin('');}}}><label>Sample parent PIN<input type="password" aria-label="Sample parent PIN" inputMode="numeric" autoComplete="off" maxLength="4" value={pin} onChange={e=>enter(e.target.value)}/></label><div className="bgd-pin-dots" aria-label={`${pin.length} of 4 digits entered`}>{[0,1,2,3].map(i=><span className={i<pin.length?'filled':''} key={i}/>)}</div><div className="bgd-keypad">{['1','2','3','4','5','6','7','8','9','0'].map(n=><button type="button" key={n} onClick={()=>enter(pin+n)}>{n}</button>)}<button type="button" aria-label="Delete PIN digit" onClick={()=>enter(pin.slice(0,-1))}>Delete</button><button className="bgd-primary" disabled={pin.length!==4}>Unlock</button></div>{pinError&&<p className="bgd-error" role="alert">{pinError}</p>}</form></div></div>;
  return <div className="bgd-parent"><header className="bgd-app-header"><Brand/><span className="bgd-local">Local preview · no account</span></header><div className="bgd-parent-heading"><div><span className="bgd-kicker">Parent Controls</span><h3>Layers Guard</h3><p>Sample parent session active</p></div><div className="bgd-heading-actions"><Badge state={state}/><button onClick={()=>setLocked(true)}><Icon name="lock"/>Lock now</button></div></div>
    <nav className="bgd-tabs" role="tablist" aria-label="Browser Guard Parent Controls" onKeyDown={e=>{const ids=Object.keys(titles),i=ids.indexOf(tab);let next;if(e.key==='ArrowRight')next=ids[(i+1)%ids.length];if(e.key==='ArrowLeft')next=ids[(i+ids.length-1)%ids.length];if(e.key==='Home')next=ids[0];if(e.key==='End')next=ids.at(-1);if(next){e.preventDefault();setTab(next);e.currentTarget.querySelector(`#bgd-tab-${next}`)?.focus();}}}>{Object.keys(titles).map(t=><button role="tab" key={t} id={`bgd-tab-${t}`} aria-selected={tab===t} aria-controls="bgd-panel" tabIndex={tab===t?0:-1} onClick={()=>setTab(t)}>{t[0].toUpperCase()+t.slice(1)}</button>)}</nav>
    <section id="bgd-panel" role="tabpanel" aria-labelledby={`bgd-tab-${tab}`}><div className="bgd-section-heading"><span className="bgd-kicker">{tab}</span><h3>{titles[tab]}</h3></div>
      {tab==='overview'&&<><div className={`bgd-health ${health(state).kind}`}><Icon name="shield"/><div><strong>{health(state).title}</strong><p>{health(state).reason}</p></div></div><div className="bgd-summary">{[
        ['globe','Website blocking',`${state.rules.filter(r=>r.enabled).length} websites protected`,`${state.rules.filter(r=>activeRule(r,state.time)).length} blocked now`,'websites'],
        ['content','Content Protection',state.scanner?'Enabled':'Off',`${state.monitored.length} services selected`,'content'],
        ['clock','Bedtime Protection',state.bedtime.enabled?`${state.bedtime.start}–${state.bedtime.end}`:'Off',state.bedtime.enabled&&timeInRange(state.time,state.bedtime.start,state.bedtime.end)?'Active now':'Choose quiet hours','schedule'],
        ['lock','Incognito Protection',state.incognito?'Enabled in sample':'Not enabled','Chrome controls this permission','settings']
      ].map(([icon,label,value,detail,target])=><button className="bgd-summary-card" key={label} onClick={()=>setTab(target)}><Icon name={icon}/><span>{label}</span><strong>{value}</strong><small>{detail}</small></button>)}</div><div className="bgd-card"><h4>Protect against browser bypasses</h4><p>Secure Mode is not verified in this sample browser. Guest Mode, other profiles and extension removal can bypass a normal extension.</p><a href="guard-windows.html">Read the Windows Secure Mode guide</a></div><Alerts state={state}/></>}
      {tab==='websites'&&<Websites key={resetId} state={state} dispatch={dispatch} notify={notify}/>}
      {tab==='schedule'&&<><div className="bgd-card"><div className="bgd-row"><div><h4>Enable Bedtime Protection</h4><p>{state.bedtime.enabled?`${state.bedtime.start}–${state.bedtime.end} · ${timeInRange(state.time,state.bedtime.start,state.bedtime.end)?'Active now':'Scheduled'}`:'No bedtime restriction is configured.'}</p></div><Toggle label="Enable Bedtime Protection" checked={state.bedtime.enabled} onChange={()=>dispatch({type:'bedtime',value:{enabled:!state.bedtime.enabled}})}/></div><Times prefix="Bedtime" start={state.bedtime.start} end={state.bedtime.end} setStart={start=>dispatch({type:'bedtime',value:{start}})} setEnd={end=>dispatch({type:'bedtime',value:{end}})}/><p className="bgd-save">Changes apply to the sample browser immediately.</p></div><div className="bgd-callout"><Icon name="clock"/><p>Try 23:00 in the preview clock, then open Sample browsing. Bedtime restricts browsing across the sample sites.</p></div></>}
      {tab==='content'&&<><div className="bgd-card"><div className="bgd-row"><div><h4>Turn on Content Protection</h4><p>Analyze visible page text locally on selected websites.</p></div><Toggle label="Turn on Content Protection" checked={state.scanner} onChange={()=>dispatch({type:'scanner'})}/></div><fieldset><legend>Sensitivity</legend><div className="bgd-choices">{[['standard','Standard','Threats and explicit content'],['strict','Strict','Also bullying, insults and grooming patterns']].map(([value,label,detail])=><label className="bgd-choice" key={value}><input type="radio" name="bgd-sensitivity" value={value} checked={state.sensitivity===value} onChange={()=>dispatch({type:'sensitivity',value})}/><span><strong>{label}</strong><small>{detail}</small></span></label>)}</div></fieldset><fieldset><legend>Protected websites</legend><div className="bgd-monitored">{scanSites.map(s=><label className="bgd-check" key={s}><input type="checkbox" checked={state.monitored.includes(s)} onChange={()=>dispatch({type:'monitor',value:s})}/>{s}</label>)}</div></fieldset></div><Alerts state={state} clear={()=>{dispatch({type:'clear-alerts'});notify('Sample alert history cleared.');}}/><div className="bgd-callout"><Icon name="shield"/><p>Preclassified examples demonstrate the interface here. The actual extension scans locally and can miss content or flag it incorrectly.</p></div></>}
      {tab==='settings'&&<><div className="bgd-card"><h4>Incognito Protection</h4><p>Chrome’s “Allow in Incognito” setting controls this permission in the real extension.</p><label className="bgd-check"><input type="checkbox" checked={state.incognito} onChange={()=>dispatch({type:'incognito'})}/>Simulate Incognito permission enabled</label><small>This only changes the preview’s status.</small></div><div className="bgd-card"><div className="bgd-row"><div><h4>Parent session security</h4><p>The parent PIN protects extension settings. The real app locks after inactivity.</p></div><button onClick={()=>setLocked(true)}>Lock now</button></div><p>Try the sample PIN 1234. No PIN is saved by this preview.</p></div><div className="bgd-card"><h4>What the PIN protects</h4><p>The PIN cannot stop an administrator changing Chrome or Windows. Other browsers are outside this extension’s scope.</p><a href="guard-windows.html">Windows Secure Mode guidance</a></div></>}
    </section>
  </div>;
}

function Popup({state,close,openParent}) {
  const enabled=state.rules.filter(r=>r.enabled).length, active=state.rules.filter(r=>activeRule(r,state.time)).length;
  return <aside className="bgd-popup" aria-label="Layers Guard extension popup"><div className="bgd-popup-head"><Brand/><button aria-label="Close extension popup" onClick={close}><Icon name="close"/></button></div><div className="bgd-popup-health"><span className="bgd-kicker">Protection status</span><h3>{health(state).title}</h3><p>{health(state).reason}</p></div><div className="bgd-popup-list">{[
    ['globe','Website blocking',enabled?`${enabled} websites protected`:'No websites configured',active?'Blocked now':'Scheduled'],
    ['clock','Bedtime Protection',state.bedtime.enabled?`${state.bedtime.start}–${state.bedtime.end}`:'Bedtime is off',''],
    ['content','Content Protection',`${state.monitored.length} selected services`,state.scanner?'On':'Off'],
    ['shield','Recent alerts',`${state.alerts.filter(a=>!a.read).length} unread sample alerts`,''],
    ['lock','Incognito Protection',state.incognito?'Allowed in sample':'Not enabled',state.incognito?'On':'Off'],
    ['shield','Bypass protection','Windows Secure Mode not verified','Limited']
  ].map(([icon,title,detail,status])=><div className="bgd-popup-row" key={title}><Icon name={icon}/><div><strong>{title}</strong><small>{detail}</small></div><span>{status}</span></div>)}</div><button className="bgd-primary bgd-wide" onClick={openParent}>Open Parent Controls</button><p className="bgd-popup-note">An interactive sample of the extension popup.</p></aside>;
}
function SampleBrowser({state,dispatch,openContent}) {
  const [url,setUrl]=useState(state.domain),[error,setError]=useState('');
  useEffect(()=>setUrl(state.domain),[state.domain]);
  const reason=blockedReason(state);
  return <div className="bgd-sample"><div className="bgd-visit"><form onSubmit={e=>{e.preventDefault();if(!normalizeDomain(url)){setError('Enter a valid domain or http/https URL.');return;}dispatch({type:'visit',value:url});setError('');}}><label>Sample website<input aria-label="Sample website" value={url} onChange={e=>setUrl(e.target.value)}/></label><button>Visit sample</button></form><p>No real website is opened. Choose a scenario or enter a domain to test your rules.</p>{error&&<p className="bgd-error" role="alert">{error}</p>}<div className="bgd-scenarios">{[['learn.example.org','Study page'],['youtube.com','Distraction site'],['reddit.com','Content example']].map(([domain,label])=><button key={domain} aria-pressed={state.domain===domain} onClick={()=>dispatch({type:'visit',value:domain})}>{label}</button>)}</div></div>
    {reason?<div className="bgd-blocked"><div className="bgd-blocked-mark"><Icon name={reason.type==='bedtime'?'clock':'shield'}/></div><span className="bgd-kicker">Protected by Layers Guard · sample</span><h3>{reason.type==='bedtime'?'It’s time for a break':'This website is blocked'}</h3><p>{state.domain}</p><div className="bgd-reason"><small>WHY?</small><strong>{reason.type==='bedtime'?'Bedtime Protection is active.':'This site has been restricted by your parent or guardian.'}</strong><small>WHEN?</small><span>{reason.type==='bedtime'?`Available after ${reason.end}.`:reason.rule.schedule?`Blocked from ${reason.rule.schedule.start} to ${reason.rule.schedule.end}.`:'This rule is always active.'}</span></div><button className="bgd-primary" onClick={()=>dispatch({type:'visit',value:'learn.example.org'})}><Icon name="back"/>Go back to the study page</button></div>:state.domain==='reddit.com'?<div className="bgd-community"><div className="bgd-feed-heading"><span>Community discussion</span><small>Preclassified content examples</small></div><h3>A quieter conversation.</h3><p>Harmless placeholder posts demonstrate what the extension’s blur and alert treatment looks like.</p>{[['threat','Threat','High'],['bullying','Bullying','Medium']].map(([id,category,severity])=><div className="bgd-post" key={id}><div className={contentHidden(state,id)?'bgd-blurred':''} aria-hidden={contentHidden(state,id)}><small>Sample member · 5 minutes ago</small><strong>{id==='threat'?'Placeholder for a high-severity content example.':'Placeholder for a bullying content example.'}</strong><p>No harmful messages are displayed in this preview.</p></div>{contentHidden(state,id)&&<div className="bgd-content-overlay"><Icon name="shield"/><strong>Potentially harmful content hidden</strong><span>{category} · {severity}</span></div>}</div>)}<button onClick={openContent}>Review sample safety alerts</button></div>:<div className="bgd-study"><div className="bgd-study-heading"><strong>Fieldnotes</strong><span>Explore · Learn · Discover</span></div><span className="bgd-study-kicker">A little curiosity goes a long way</span><h3>There’s a whole world<br/>outside the screen.</h3><div className="bgd-landscape" aria-hidden="true"><span/><span/><span/><span/></div><p>A sample learning page at <strong>{state.domain}</strong>. This domain is available under your current rules.</p><div className="bgd-study-cards"><div><strong>Look a little closer.</strong><span>What can you spot on a walk?</span></div><div><strong>Make room for wonder.</strong><span>Bring your questions along.</span></div></div></div>}
  </div>;
}
function BrowserGuardDemo() {
  const [state,dispatch]=useReducer(guardReducer,undefined,initialGuard),[view,setView]=useState('parent'),[tab,setTab]=useState('overview'),[popup,setPopup]=useState(false),[locked,setLocked]=useState(false),[message,setMessage]=useState(''),[resetId,setResetId]=useState(0);
  const popupButton=useRef(null),popupRef=useRef(null),workspace=useRef(null);
  useEffect(()=>{if(workspace.current)workspace.current.scrollTop=0;},[view,tab,locked,resetId]);
  useEffect(()=>{if(view==='browser')dispatch({type:'scan'});},[view,state.domain,state.scanner,state.sensitivity,state.monitored,state.time,state.rules,state.bedtime]);
  useEffect(()=>{if(view==='parent'&&!locked&&tab==='content')dispatch({type:'read-alerts'});},[view,tab,locked]);
  useEffect(()=>{if(!popup)return;popupRef.current?.querySelector('button')?.focus({preventScroll:true});const close=e=>{if(!popupRef.current?.contains(e.target)&&!popupButton.current?.contains(e.target))setPopup(false);};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close);},[popup]);
  function openParent(next=tab) {setView('parent');setTab(next);setPopup(false);}
  function reset() {dispatch({type:'reset'});setView('parent');setTab('overview');setPopup(false);setLocked(false);setResetId(n=>n+1);setMessage('Browser Guard preview reset.');}
  return <div className="browser-guard-demo" onKeyDown={e=>{if(e.key==='Escape'&&popup){setPopup(false);popupButton.current?.focus();}}}>
    <div className="bgd-intro"><div><span className="eyebrow">Interactive extension preview</span><h2>Your rules. Their browser.</h2><p>Try the extension’s parent controls, then switch to sample browsing to see the result.</p></div><button className="bgd-reset" onClick={reset}><Icon name="reset"/>Reset preview</button></div>
    <div className="bgd-demo-bar"><span>Everything here uses sample data.</span><label>Preview clock<input type="time" aria-label="Preview clock" value={state.time} onInput={e=>dispatch({type:'time',value:e.target.value})} onChange={e=>dispatch({type:'time',value:e.target.value})}/></label><div className="bgd-clock-presets" aria-label="Preview time examples"><button aria-pressed={state.time==='20:30'} onClick={()=>dispatch({type:'time',value:'20:30'})}>Evening · 20:30</button><button aria-pressed={state.time==='23:00'} onClick={()=>dispatch({type:'time',value:'23:00'})}>Night · 23:00</button></div><button onClick={()=>{setView('browser');setPopup(false);}}>Try sample browsing</button></div>
    <div className={`bgd-browser-frame ${popup?'bgd-popup-open':''}`}><div className="bgd-browser-tabs"><div className="bgd-window-dots" aria-hidden="true"><span/><span/><span/></div><button aria-pressed={view==='parent'} onClick={()=>{setView('parent');setPopup(false);}}><Icon name="shield"/>Parent Controls</button><button aria-pressed={view==='browser'} onClick={()=>{setView('browser');setPopup(false);}}><Icon name="globe"/>Sample browsing</button></div><div className="bgd-addressbar"><Icon name="lock"/><span>{view==='parent'?'Layers Guard / Parent Controls':`https://${state.domain}`}</span><button ref={popupButton} aria-label="Open extension popup" aria-expanded={popup} onClick={()=>setPopup(!popup)}><Icon name="shield"/></button></div>
      <div ref={workspace} className="bgd-workspace">{view==='parent'?<ParentControls key={resetId} state={state} dispatch={dispatch} tab={tab} setTab={setTab} locked={locked} setLocked={setLocked} notify={setMessage} resetId={resetId}/>:<SampleBrowser state={state} dispatch={dispatch} openContent={()=>openParent('content')}/>}</div>
      {popup&&<div ref={popupRef}><Popup state={state} close={()=>{setPopup(false);popupButton.current?.focus();}} openParent={()=>openParent()}/></div>}
    </div><p className="bgd-footnote">This is the browser extension preview. Browser Guard works within its configured browser and is separate from Guard Family’s Windows and Android device controls. <a href="contact.html?topic=browser-guard">Join the free closed beta</a>.</p><p className="bgd-live" role="status" aria-live="polite">{message}</p>
  </div>;
}
for(const host of document.querySelectorAll('[data-browser-guard-demo]'))createRoot(host).render(<BrowserGuardDemo/>);
