import React, {useState, useSyncExternalStore} from 'react';
import {createRoot} from 'react-dom/client';
import {devices, initialState, reduceDemo, formatTime} from './demo-state.mjs';

let state = initialState();
const listeners = new Set();
const dispatch = action => {state = reduceDemo(state, action); listeners.forEach(fn => fn());};
const subscribe = fn => {listeners.add(fn); return () => listeners.delete(fn);};
const useDemo = () => useSyncExternalStore(subscribe, () => state);
const language = document.documentElement.lang || 'en';
const translations = {
  ja: {Today:'今日', Trends:'傾向', Controls:'設定', Inbox:'リクエスト', Alerts:'通知', Settings:'その他', 'Try the app':'アプリを試す', 'Interactive demo':'操作できるデモ', 'Sample data · no account needed':'サンプルデータ · アカウント不要', 'Reset demo':'デモをリセット', 'Web dashboard':'ウェブ管理画面', 'Android Controller':'Android Controller', 'Explore the app':'アプリを体験', 'Screen Time':'利用時間', 'Pause internet':'通信を停止', 'Resume internet':'通信を再開', 'Lock device':'端末をロック', 'Unlock device':'ロック解除', 'Add 15 min':'15分追加', 'Daily allowance':'1日の利用時間', 'Bedtime lockout':'就寝時間', Approve:'承認', Decline:'拒否'},
  zh: {Today:'今天', Trends:'趋势', Controls:'控制', Inbox:'请求', Alerts:'提醒', Settings:'设置', 'Try the app':'体验应用', 'Interactive demo':'交互式演示', 'Sample data · no account needed':'示例数据 · 无需账户', 'Reset demo':'重置演示', 'Web dashboard':'网页控制面板', 'Android Controller':'Android Controller', 'Explore the app':'探索应用', 'Screen Time':'屏幕时间', 'Pause internet':'暂停网络', 'Resume internet':'恢复网络', 'Lock device':'锁定设备', 'Unlock device':'解锁设备', 'Add 15 min':'增加15分钟', 'Daily allowance':'每日使用时长', 'Bedtime lockout':'就寝锁定', Approve:'批准', Decline:'拒绝'},
  vi: {Today:'Hôm nay', Trends:'Xu hướng', Controls:'Điều khiển', Inbox:'Yêu cầu', Alerts:'Cảnh báo', Settings:'Cài đặt', 'Try the app':'Trải nghiệm ứng dụng', 'Interactive demo':'Bản demo tương tác', 'Sample data · no account needed':'Dữ liệu mẫu · Không cần tài khoản', 'Reset demo':'Đặt lại demo', 'Web dashboard':'Bảng điều khiển web', 'Android Controller':'Android Controller', 'Explore the app':'Khám phá ứng dụng', 'Screen Time':'Thời gian sử dụng', 'Pause internet':'Tạm dừng mạng', 'Resume internet':'Bật lại mạng', 'Lock device':'Khóa thiết bị', 'Unlock device':'Mở khóa', 'Add 15 min':'Thêm 15 phút', 'Daily allowance':'Giới hạn hằng ngày', 'Bedtime lockout':'Giờ đi ngủ', Approve:'Chấp thuận', Decline:'Từ chối'}
};
const t = text => translations[language]?.[text] || text;
function Icon({name}) {
  const paths = {shield:<><path d="m12 2 8 4v6c0 5-8 10-8 10S4 17 4 12V6z"/><path d="m8 12 3 3 5-6"/></>,today:<><rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/></>,trends:<path d="m3 17 6-6 4 4 8-10M15 5h6v6"/>,controls:<><path d="M4 7h16M4 17h16"/><circle cx="8" cy="7" r="3"/><circle cx="16" cy="17" r="3"/></>,inbox:<><path d="M4 4h16l2 14H2zM2 13h6l2 3h4l2-3h6"/></>,alerts:<><path d="M5 17h14l-2-3V9a5 5 0 0 0-10 0v5zM10 21h4"/></>,settings:<><circle cx="12" cy="12" r="3"/><path d="m9 3 6 0 1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1z"/></>,windows:<><rect x="2" y="3" width="20" height="14" rx="2"/><path d="M8 21h8M12 17v4"/></>,android:<><rect x="6" y="2" width="12" height="20" rx="3"/><path d="M10 18h4"/></>,lock:<><rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></>,wifi:<><path d="M2 8a16 16 0 0 1 20 0M5 12a11 11 0 0 1 14 0M8 16a6 6 0 0 1 8 0"/><circle cx="12" cy="20" r="1"/></>,clock:<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>};
  return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name] || paths.shield}</svg>;
}
const tabs = ['today','trends','controls','inbox','alerts','settings'];
const title = key => t(key[0].toUpperCase() + key.slice(1));
function TabButton({tab, label, icon=true}) {const s=useDemo();return <button type="button" className={s.tab===tab?'selected':''} aria-label={label || title(tab)} aria-pressed={s.tab===tab} onClick={()=>dispatch({type:'tab',value:tab})}>{icon&&<Icon name={tab}/>}<span>{label || title(tab)}</span>{tab==='inbox'&&s.requests.length>0&&<b className="demo-badge">{s.requests.length}</b>}</button>;}
function DeviceSelect({compact=false}) {const s=useDemo();return <div className={'demo-devices '+(compact?'compact':'')} aria-label="Sample child devices">{Object.entries(devices).map(([id,d])=><button key={id} type="button" aria-pressed={s.device===id} className={s.device===id?'selected':''} onClick={()=>dispatch({type:'device',value:id})}><Icon name={id}/><span>{d.name}<small>{d.platform} · Sample online</small></span><i/></button>)}</div>;}
function Ring({small=false}) {const s=useDemo(),d=devices[s.device],rule=s.rules[s.device],percentage=Math.min(100,d.used/rule.limit*100);return <div className={'demo-ring '+(small?'small':'')} style={{'--progress':`${percentage}%`}}><div><strong>{formatTime(d.used)}</strong><span>of {formatTime(rule.limit)}</span></div></div>;}
function QuickActions() {const s=useDemo(),r=s.rules[s.device];return <div className="demo-quick"><button type="button" onClick={()=>dispatch({type:'lock'})}><Icon name="lock"/>{t(r.locked?'Unlock device':'Lock device')}</button><button type="button" onClick={()=>dispatch({type:'extend',minutes:15})}><Icon name="clock"/>{t('Add 15 min')}</button><button type="button" onClick={()=>dispatch({type:'pause'})}><Icon name="wifi"/>{t(r.paused?'Resume internet':'Pause internet')}</button></div>;}
function Apps({controls=false}) {const s=useDemo(),r=s.rules[s.device];const names=controls?[...devices[s.device].apps.map(x=>x[0]),'TikTok']:devices[s.device].apps.map(x=>x[0]);return <div className="demo-apps">{names.map((name,i)=><div key={name} className="demo-app"><span className={'app-tile tile-'+i}>{name[0]}</span><span>{name}<small>{controls?'App restriction':formatTime(devices[s.device].apps[i]?.[1]||0)}</small></span>{controls?<button type="button" onClick={()=>dispatch({type:'app',value:name})} aria-label={(r.blockedApps.includes(name)?'Unblock ':'Block ')+name} aria-pressed={r.blockedApps.includes(name)} className={r.blockedApps.includes(name)?'blocked':''}>{r.blockedApps.includes(name)?'Blocked':'Allowed'}</button>:<span className="app-meter"><i style={{width:`${95-i*25}%`}}/></span>}</div>)}</div>;}
function Chart() {const s=useDemo(),week=s.period==='week',values=week?[48,70,35,88,55,73,62]:[12,22,45,30,72,88,42];return <div className="demo-chart" role="img" aria-label={week?'Sample daily screen time for the last seven days':'Sample screen time by hour today'}>{values.map((v,i)=><div key={i}><span>{week?[ '1h 26','2h 06','1h 03','2h 38','1h 39','2h 11','2h 14'][i]:['10m','18m','36m','24m','58m','1h 10','34m'][i]}</span><i style={{height:`${v}%`}}/><small>{week?['M','T','W','T','F','S','S'][i]:['9','10','11','12','13','14','15'][i]}</small></div>)}</div>;}
function Requests() {const s=useDemo();return <div className="demo-requests">{s.requests.length?s.requests.map(req=><div className="demo-request" key={req.id}><div><strong>{devices[req.device].name}</strong><p>“Can I have 15 more minutes?”</p><small>More screen time · sample request</small></div><div className="demo-request-actions"><button type="button" onClick={()=>dispatch({type:'resolve',id:req.id,approve:true})}>{t('Approve')}</button><button type="button" onClick={()=>dispatch({type:'resolve',id:req.id,approve:false})}>{t('Decline')}</button></div></div>):<p className="demo-empty">✓ No requests waiting. Try asking for more time on the child’s screen.</p>}</div>;}
function Controls({id}) {const s=useDemo(),r=s.rules[s.device];const [domain,setDomain]=useState('');return <div className="demo-controls">
  <div className="demo-card"><div className="demo-card-heading"><strong>{t('Daily allowance')}</strong><b>{formatTime(r.limit)}</b></div><label htmlFor={id+'-limit'}>Minutes per day</label><input id={id+'-limit'} type="range" min="30" max="480" step="15" value={r.limit} onChange={e=>dispatch({type:'limit',value:e.target.value})}/><div className="demo-scale"><span>30 min</span><span>8 hours</span></div></div>
  <div className="demo-card"><div className="demo-card-heading"><strong>{t('Bedtime lockout')}</strong><button type="button" role="switch" aria-label="Enable bedtime lockout" aria-checked={r.bedtimeOn} className={'demo-toggle '+(r.bedtimeOn?'on':'')} onClick={()=>dispatch({type:'bedtimeOn'})}><span/></button></div><label htmlFor={id+'-bedtime'}>Bedtime starts</label><input id={id+'-bedtime'} type="time" value={r.bedtime} disabled={!r.bedtimeOn} onChange={e=>dispatch({type:'bedtime',value:e.target.value})}/><small>Sample schedule · wakes at 07:00</small></div>
  <div className="demo-card"><strong>Blocked apps</strong><Apps controls/></div><div className="demo-card"><strong>Blocked websites</strong><form onSubmit={e=>{e.preventDefault();dispatch({type:'site',value:domain});setDomain('');}}><label htmlFor={id+'-website'}>Website domain</label><div className="demo-site-input"><input id={id+'-website'} value={domain} placeholder="example.org" maxLength="120" onChange={e=>setDomain(e.target.value)}/><button type="submit">Block</button></div></form>{r.blockedSites.map(site=><div className="demo-site" key={site}><span>{site}</span><button type="button" aria-label={'Remove '+site} onClick={()=>dispatch({type:'removeSite',value:site})}>Remove</button></div>)}</div>
</div>;}
function Content({id,compact=false}) {const s=useDemo(),d=devices[s.device],r=s.rules[s.device];if(s.tab==='controls')return <Controls id={id}/>;
if(s.tab==='inbox')return <div className="demo-card"><strong>Awaiting your approval</strong><Requests/></div>;
if(s.tab==='alerts')return <div className="demo-card"><strong>Content alerts</strong>{s.alerts?<><p>A potentially harmful phrase was flagged in the sample browser session.</p><p className="demo-muted">Review the context together. Alerts can miss content or flag it incorrectly.</p><button type="button" className="demo-primary" onClick={()=>dispatch({type:'alert'})}>Mark as reviewed</button></>:<p className="demo-empty">✓ Sample alert reviewed.</p>}</div>;
if(s.tab==='settings')return <div className="demo-card"><strong>Your parent account</strong><p>This preview uses sample devices. The real dashboard includes account settings, pairing and parent PIN controls.</p><p className="demo-muted">Your changes here stay in this demo until the page reloads.</p><button type="button" className="demo-primary" onClick={()=>dispatch({type:'reset'})}>{t('Reset demo')}</button></div>;
if(s.tab==='trends')return <><div className="demo-card"><div className="demo-card-heading"><strong>{s.period==='week'?'Last 7 days':'Screen time by hour'}</strong><div className="demo-segment">{['day','week'].map(p=><button type="button" key={p} aria-pressed={s.period===p} className={s.period===p?'selected':''} onClick={()=>dispatch({type:'period',value:p})}>{p==='week'?'Week':'Day'}</button>)}</div></div><Chart/></div><div className="demo-card"><strong>Most used apps</strong><Apps/></div></>;
return <><div className="demo-screen-time"><Ring small={compact}/><div><h3>{t('Screen Time')}</h3><p>Here’s how today is going</p><div className="demo-stats"><span><b>{formatTime(d.used)}</b>Used</span><span><b>{formatTime(Math.max(0,r.limit-d.used))}</b>Remaining</span></div></div></div><div className="demo-protection"><Icon name="shield"/><span>Protected · sample device</span></div><QuickActions/>{!compact&&<><div className="demo-next"><Icon name="clock"/><span>{r.bedtimeOn?`Bedtime begins at ${r.bedtime}`:'Bedtime is off'} · {r.paused?'Internet paused':'Internet available'}</span></div><div className="demo-card"><strong>Open right now</strong><Apps/></div></>}</>;
}
function ParentScreen({id,compact=false,phone=false}) {const s=useDemo();return <div className={'demo-dashboard '+(phone?'phone-dashboard':'')}>
 {!phone&&<aside className="demo-sidebar"><div className="demo-brand"><Icon name="shield"/><b>Layers<span>GUARD</span></b></div><DeviceSelect compact={compact}/><nav aria-label="Demo sidebar">{tabs.map(tab=><TabButton key={tab} tab={tab}/>)}</nav><small>Parent view · Sample data</small></aside>}
 <div className="demo-main">{phone&&<DeviceSelect compact/>}<div className="demo-greeting"><div><strong>Good morning</strong><p>Viewing {devices[s.device].name}</p></div><span className="demo-online">Online</span></div><div className="demo-tabs" aria-label="Demo app screens">{['today','trends','controls'].map(tab=><TabButton key={tab} tab={tab} icon={false}/>)}</div><div className="demo-panel"><Content id={id} compact={compact}/></div>{phone&&<nav className="demo-phone-more" aria-label="More demo screens">{['inbox','alerts','settings'].map(tab=><TabButton key={tab} tab={tab}/>)}</nav>}</div>
</div>;}
function BrowserFrame({id,compact}) {return <div className={'demo-laptop '+(compact?'compact':'')}><div className="demo-browser-bar"><span className="demo-browser-dots"><i/><i/><i/></span><span><Icon name="lock"/>thelayersapp.com/dashboard</span><small>Demo</small></div><ParentScreen id={id} compact={compact}/><div className="demo-laptop-base"/></div>;}
function PhoneFrame({children,className=''}) {return <div className={'demo-phone '+className}><div className="demo-phone-camera"/><div className="demo-phone-glass"><div className="demo-statusbar"><span>9:41</span><span>▰ ▰</span></div>{children}<div className="demo-home-indicator"/></div></div>;}
function WindowsChild() {const s=useDemo(),d=devices.windows,r=s.rules.windows;return <div className={'demo-windows-child '+(r.locked?'is-locked':'')}><div className="demo-window-title"><span>Layers Guard</span><span>− □ ×</span></div><div className="windows-child-header"><Icon name="shield"/><div><strong>Layers Guard</strong><small>{d.name}</small></div></div>{r.locked?<div className="windows-lock"><Icon name="lock"/><h3>Computer paused</h3><p>Your parent has temporarily paused this computer.</p><button type="button" onClick={()=>dispatch({type:'request',device:'windows'})}>Request more time</button></div>:<div className="windows-child-body"><div className="windows-child-card"><strong>Screen time today</strong><small>{formatTime(d.used)} used</small><h3>{formatTime(Math.max(0,r.limit-d.used))} remaining</h3><p>Daily limit: {formatTime(r.limit)}</p><div className="windows-progress"><i style={{width:`${Math.min(100,d.used/r.limit*100)}%`}}/></div><p>Your screen time is managed by your parent.</p></div><div className="windows-child-card"><strong>Current protection</strong><p>{r.paused?'Internet paused':'Connected · Sample protection active'}</p><p>Bedtime: {r.bedtimeOn?r.bedtime:'Off'}</p><p>{r.blockedApps.length} app rules · {r.blockedSites.length} website rules</p></div><div className="windows-child-card"><strong>What would you like to do?</strong><button type="button" onClick={()=>dispatch({type:'request',device:'windows'})}>Request more time</button></div><small>Managed with Layers Guard · sample data</small></div>}</div>;}
function ChildScreen() {const s=useDemo(),d=devices[s.device],r=s.rules[s.device];return <div className={'demo-child '+(r.locked?'is-locked':'')}><Icon name={r.locked?'lock':'shield'}/><span className="demo-child-label">{d.app}</span><h3>{r.locked?'Time for a break':r.paused?'Internet is paused':'You’re all set'}</h3><p>{r.locked?'Your parent has locked this sample device.':r.paused?'Offline apps are still available.':'Your family’s rules are in place.'}</p><div className="demo-child-details"><span>Time remaining<b>{formatTime(Math.max(0,r.limit-d.used))}</b></span><span>Bedtime<b>{r.bedtimeOn?r.bedtime:'Off'}</b></span><span>App rules<b>{r.blockedApps.length} blocked</b></span></div><button type="button" className="demo-primary" onClick={()=>dispatch({type:'request'})}>Ask for 15 more minutes</button><small>Sample child screen · {d.platform}</small></div>;}
function MiniController() {const s=useDemo(),r=s.rules[s.device];return <PhoneFrame className="demo-parent-phone controller-frame"><div className="mini-controller"><span className="mini-wordmark">Layers Guard</span><strong>{devices[s.device].name}</strong><small>Android Controller · Sample data</small>{s.tab==='today'?<><Ring small/><div className="mini-info"><span>{t('Bedtime lockout')}<b>{r.bedtimeOn?r.bedtime:'Off'}</b></span></div><button type="button" className={'mini-pause '+(r.paused?'paused':'')} onClick={()=>dispatch({type:'pause'})}><Icon name="wifi"/><span>{t(r.paused?'Resume internet':'Pause internet')}<small>{r.paused?'Paused':'Internet available'}</small></span><i/></button></>:<div className="mini-demo-content"><Content id="mini-controller" compact/></div>}<div className="demo-tabs">{['today','trends','controls'].map(tab=><TabButton key={tab} tab={tab} icon={false}/>)}</div></div></PhoneFrame>;}
const explanations = {today:['A little more time. A calmer evening.','Try locking a device, adding time, or pausing the internet. The sample child screen responds to your changes.'],trends:['Understand their day.','Switch between daily and weekly sample activity, and explore the apps they spend time in.'],controls:['Rules that fit your family.','Change the daily allowance and bedtime, or block an app and website. Rules belong to the selected child device.'],inbox:['Keep the conversation going.','Approve or decline a sample request. Approval adds 15 minutes to that child’s allowance.'],alerts:['A signal to check together.','Explore a sample content alert. In the real app, review context before deciding what to do.'],settings:['A place for parent settings.','This walkthrough is separate from your account. Reset it whenever you want to start again.']};
function Showcase({id,compact=false}) {const s=useDemo();return <div className={'guard-showcase '+(compact?'showcase-compact':'showcase-expanded')}>
 {compact?<><div className="demo-stage"><BrowserFrame id={id} compact/><MiniController/><div className="demo-floating-chip"><Icon name="shield"/><span>Windows + Android<small>One parent view</small></span></div></div><div className="demo-caption"><span><i/>{t('Interactive demo')}</span><a href="#demo">{t('Explore the app')} →</a></div></>:<>
 <div className="demo-heading"><div><span className="eyebrow">{t('Try the app')}</span><h2>Tap around. See what changes.</h2><p>{t('Sample data · no account needed')}</p></div><button type="button" className="demo-reset" onClick={()=>dispatch({type:'reset'})}>{t('Reset demo')} ↺</button></div>
 <div className="demo-tour-nav" aria-label="Explore demo screens">{tabs.map(tab=><TabButton key={tab} tab={tab}/>)}</div><div className="demo-explanation"><strong>{explanations[s.tab][0]}</strong><p>{explanations[s.tab][1]}</p></div>
 <div className="demo-view-switch" aria-label="Parent demo format">{[['browser','Web dashboard'],['controller','Android Controller']].map(([view,label])=><button type="button" key={view} aria-pressed={s.view===view} className={s.view===view?'selected':''} onClick={()=>dispatch({type:'view',value:view})}><Icon name={view==='browser'?'windows':'android'}/>{t(label)}</button>)}</div>
 <div className={'demo-workspace '+(s.view==='controller'?'controller-view':'')}><div className="demo-parent-view"><span className="demo-view-label">PARENT VIEW</span>{s.view==='browser'?<BrowserFrame id={id}/>:<PhoneFrame className="controller-frame"><ParentScreen id={id} phone/></PhoneFrame>}</div><div className="demo-child-view"><span className="demo-view-label">CHILD’S DEVICE · {devices[s.device].platform.toUpperCase()}</span>{s.device==='windows'?<WindowsChild/>:<PhoneFrame className="child-frame"><ChildScreen/></PhoneFrame>}</div></div>
 <p className="demo-feedback" role="status" aria-live="polite" aria-atomic="true">{s.message || 'Choose a screen above, or click a control inside the app.'}</p><p className="demo-footnote">An interactive product walkthrough with sample data. Real device status, permissions and connection determine when controls take effect.</p>
 </>}
 </div>;}
document.querySelectorAll('[data-guard-demo]').forEach((host,index)=>createRoot(host).render(<Showcase id={'guard-demo-'+index} compact={host.dataset.guardDemo==='compact'}/>));
